version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pagerduty
      POSTGRES_USERNAME: pagerduty
      POSTGRES_PASSWORD: password
